### ISSUE TITLE
CSS for like button  (CSS + little bit Reactjs required)

### ISSUE THREAD

**Issue by Engineervinay** [Engineervinay/threads-clone#2]
If the thread is already liked then the like should be filled with the color red.
we already have the user IDs of the users who liked the thread we just have to see if the current user ID is present in that likes array.
if it is then display like as red color.

**Comment by Jkayed** [comment]
Hey, Vinay hope you're doing well!  

do you still need help with this? If so I'd love to help!

**Comment by Engineervinay** [comment]
Hey @Yuroq Thank You I will assign this issue to you, Please message me if you have any doubt regarding project.

**Comment by Yuroq** [comment]
Sounds good, thank you! I opened the repo in my vsCode and followed the steps on your readMe but all I get is a black screen when I open the app on Localhost, any idea? Might be related to the json server

**Comment by Jkayed** [comment]
Sounds good, Thank you!

**Comment by Engineervinay** [comment]
Start json server first then start npm start in other terminal.

**Comment by Jkayed** [comment]
I started working on the dislike feature yesterday and got that done, I'm currently working on adding the color red if the user has liked the thread and removing the color once they dislike it. I'll update you once that is done!

**Comment by Jkayed** [comment]
Hey Vinay, so I tried to add the feature where the color of the heart turns to red on the SVG but for some reason when I try to change the color on the SVG the outline is the only thing that changes on the heart so instead I the hearts from "React-Icons" and that made everything work right. The heart changes to red on like, and back to normal when thread is unliked. Are you fine with me using the heart icon from react-icons instead of an SVG?

**Comment by Engineervinay** [comment]
Yeah, No problem you can add from react-icons

**Comment by Jkayed** [comment]
I just made the PR if you have any questions let me know!

**Comment by Engineervinay** [comment]
Thanks, @Yuroq  Merged it.
